### ISSUE TITLE
Is there a way to bypass the NCBI rate-limiting e-utilities queries, causing HTTP 429 error?

### ISSUE THREAD

**Issue by amaeda16** [MVesuviusC/primerTree#35]
Hello

I am trying to use primerTree to analyze a set of primers I designed...but I have been encountering the HTTP error. I was reading in the other thread that you have made a solution but I don't know how to implement it. Is there a way I can get primerTree to work? 

Also, I have already gone through the steps of installing Clustal Omega but it still says that the command clustalo is not found

**Comment by MVesuviusC** [comment]
Hello,

I haven't pushed the potential fix over to Jim's repo, but you can give it a try like this:

```
library(devtools)
install_github("mvesuviusc/primertree", ref = "fixNcbiRateLimitIssue")
```
It works for me but please let me know if you have any issues. I'll try to get the pull request submitted so Jim can look over how I implemented the fix. It automatically limits your request rate to 3/second unless you feed it an api key from NCBI like this:
```
testRun = search_primer_pair(name='Mammals 16S', 'CGGTTGGGGTGACCTCGGA', 'GCTGTTATCCCTAGGGTAACT', api_key="xxxxxxxxxx")
```
Then it's limited to 10 requests/second. 

For your second problem, you may need to let R know where clustalo is in your path. You could try this, but replace the placeholder with the path to your clustal directory:
```
Sys.setenv('PATH'="/sbin:/usr/sbin:/bin:/usr/bin:/Path/To/The/Clustal/Directory/“)
```
and then run the primerTree command after that to see if it works.

**Comment by amaeda16** [comment]
Hi MV

Thanks so much for the help with those codes. So it seems that the NCBI and its API part has been solved, but I am still having problems with the clustalo command.
This is what I get when running the primerTree command:

BLASTing 1 primer combinations
Submitting Primer-BLAST query
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment completed in 51 seconds
500 BLAST alignments parsed in 1 seconds
taxonomy retrieved in 8 seconds
500 sequences retrieved from NCBI in 127 seconds, product length min:129 mean:134.12 max:151
sh: clustalo: command not found
Error in system(paste(exec, "--help"), intern = TRUE) : 
  error in running command

So, I tried the solution that you proposed, but still ends saying the sh: clustalo: command not found, even when I address that in the setwd command to the path where the clustalo exec file is. 

When I run the clustalo -help command in the Terminal it works, so I suppose that clustal omega is installed properly. I downloaded clustal omega again using the bioconda package. 

Also, I am working on a Mac, so I don't know if that's something that can interfere with the process

**Comment by MVesuviusC** [comment]
Did you replace my fake path with the path to your clustalo installation (the directory, not the executable)? 
@jimhester , any thoughts on other solutions to the path issue?

**Comment by jimhester** [comment]
first make sure that `primerTree::clustalo(exec = "/full/path/to/clustalo")` works. You can find where it is installed from the shell prompt with `which clustalo`. (on my system it is `/usr/local/bin/clustalo`).

If it does (it should return the same thing as just running `clustalo` on the command line), then call `search_primer_pair("xyz", "abc", clustal_options = list(exec = "/full/path/to/clustalo"))`

**Comment by amaeda16** [comment]
Hello,

Yeah, it finally got it working! It was the problem mentioned in the path to clustalo. Thanks a lot for your help, as this is a great package and visualization for my dissertation.

One more question. It looks that maybe my primer pair is resulting in a lot of information because when dealing beyond the Order level (Family, Genus and Species) it stops to put names on the nodes. 

Do you think it can be solved by resizing the plots? Some of the image parts, like some tags, are cut off. 

( I am including the image of the tree plot for you to see).
<img width="1676" alt="Screen Shot 2019-04-25 at 16 26 10" src="https://user-images.githubusercontent.com/49713702/56747995-ece8ea80-6776-11e9-9a4d-99a38f7bfdbe.png">

**Comment by MVesuviusC** [comment]
Nice, good job. 
You can force the names to display on the plot by changing the "legend_cutoff" argument in the plot() function, but honestly it just turns into a mess when there are too many. The easier way to look at the names of everything you hit is to look at the taxonomy data directly. It's in primerTreeObj$taxonomy.

**Comment by amaeda16** [comment]
Hello MV,

Thank you so much for your help during the past month. It helped me a lot for my report.

So I am testing a new primer set, but then I am getting the next error:

testRun2 = search_primer_pair(name='testrun2', 'AAACTATGATTAGCTCCAC', 'CTTAATCCAACATCGAGG', api_key="xxxxxx", num_aligns=1000)

BLASTing 1 primer combinations
Submitting Primer-BLAST query
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment completed in 51 seconds
Error in `[.data.frame`(hits, location_columns) : 
  undefined columns selected

I have checked with the Mammal_16S test pair and my past primer pairs, and they work, but I don´t know why this is error shows up, as I get the tree plots from the other ones without a hiccup. 

Any ideas why this could be happening?

**Comment by MVesuviusC** [comment]
Just a heads up, you may want to edit out your api key above, just to be careful. 

So I ran it and if I look at testRun2$response I can find the link to the raw primerBlast response:
```
> testRun2$response
$`1`
Response [https://www.ncbi.nlm.nih.gov/tools/primer-blast/primertool.cgi?ctg_time=1558106089&job_key=fnShkr4Hs6-UkbaUu_SSpsHvg5Ts_JiJ7Q]
  Date: 2019-05-17 15:15
  Status: 200
  Content-Type: text/html
  Size: 15.4 kB
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w...
<html xmlns="http://www.w3.org/1999/xhtml">
```
If you copy and paste that website (https://www.ncbi.nlm.nih.gov/tools/primer-blast/primertool.cgi?ctg_time=1558106089&job_key=fnShkr4Hs6-UkbaUu_SSpsHvg5Ts_JiJ7Q) into your browser you'll see that primerBlast couldn't find any  matches. We should likely implement error catching of some sort for this, but ultimately that's the issue.

**Comment by amaeda16** [comment]
Excellent, thanks for the heads up! I edited that already.

Oh, I see the problem. So, I have been testing the new primer pair using different mitochondrial sequences from different insect orders, and they work according to the MacVector and Geneious test. 

Do you think that maybe if I increase the mismatch option in the search primer pair, then I could get them working?

**Comment by MVesuviusC** [comment]
It's worth a try! You might also take the mtDNA from one species that you're targeting and manually align them using mafft or mega or something to see if there is anything really weird about them.

**Comment by amaeda16** [comment]
Hello again!

Thank you so much for your help during my Master's project. It help me a lot to deliver an interesting project.

I am trying to use again the package but now I am experiencing a new problem related to the api key, so I will open a new thread just in case other people are experiencing the same
